spring:
  main:
    allow-circular-references: true
    web-application-type: none
  datasource:
    hikari:
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: image_bot
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: image_bot
    schemas: image_bot
    create-schemas: true
    # Если база уже непустая и вы начинаете вести миграции с текущего состояния:
    # baseline-on-migrate: true
    # baseline-version: 0
kling:
  api:
    base-url: "https://api.klingai.com"
    image-to-video-path: "/v1/videos/image2video"

runware:
  api:
    base-url: "https://api.runware.ai/v1"
    image-to-video-path: "https://api.runware.ai/v1"

server:
  port: 55532